name: Hello World!

# on:
#   push:
#     branches:
#       - main
on:
  workflow_dispatch:

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    steps:
      - name: Say hello
        run: echo "Hello World!"

      - name: Show date
        run: date

      - name: List files
        run: ls -l
          